
import torch, numpy as np, time
from pathlib import Path

# Load test set
root = Path(__file__).parent
test_h5 = root / "torsion_well_data" / "datasets" / "torsion_1d" / "data" / "test" / "torsion_1d_test.hdf5"

import h5py
with h5py.File(test_h5, 'r') as f:
    S = f['t0_fields']['S'][:]

N_INPUT = 8
N_OUTPUT = 8
inputs, outputs = [], []
window = N_INPUT + N_OUTPUT
for traj in range(S.shape[0]):
    for t0 in range(0, S.shape[1] - window + 1):
        inputs.append(S[traj, t0:t0+N_INPUT])
        outputs.append(S[traj, t0+N_INPUT:t0+window])
inputs = np.array(inputs, dtype=np.float32)
outputs = np.array(outputs, dtype=np.float32)

# Load best GA model (generated by train_torsion_ga.py)
model_path = Path(__file__).parent / "torsion_ga_best.pt"
if not model_path.exists():
    raise FileNotFoundError("Best GA model not found: " + str(model_path))

# Define same CompactOp as in train_torsion_ga.py
import torch.nn as nn
class CompactOp(nn.Module):
    def __init__(self, ni=8, no=8, h=24):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv1d(ni, h, 7, padding=3), nn.Tanh(),
            nn.Conv1d(h, h, 5, padding=2), nn.Tanh(),
            nn.Conv1d(h, no, 5, padding=2),
        )
    def forward(self, x):
        return self.net(x)

model = CompactOp(ni=N_INPUT, no=N_OUTPUT, h=24)
model.load_state_dict(torch.load(model_path))
model.eval()

x_test = torch.from_numpy(inputs).float()
y_test = torch.from_numpy(outputs).float()
with torch.no_grad():
    pred = model(x_test).numpy()

test_mse = np.mean((outputs - pred)**2)
print(f"Test MSE: {test_mse:.6e}")
# R^2
ss_res = np.sum((outputs - pred)**2)
ss_tot = np.sum((outputs - np.mean(outputs))**2)
r2 = 1 - ss_res/ss_tot
print(f"R^2: {r2:.6f}")
